name: Release
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Generate App Bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - run: chmod +x gradlew
      - name: Build 'release' with Gradle
        run: ./gradlew assembleRelease
      - run: echo "Build status report=${{ job.status }}."
      - name: Upload Apk
        uses: actions/upload-artifact@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/app-release.apk
          asset_name: ${{ github.event.repository.name }}.apk
          asset_content_type: application/zip
      - run: echo "Upload returned with status=${{ job.status }}."